"""SLM-WM 正式论文方法实现。"""

from main.methods.carrier import (
    BlindContentScore,
    KeyedTensorCarrier,
    build_low_frequency_template,
    build_tail_robust_template,
    compute_blind_content_score,
    project_canonical_template,
)
from main.methods.detection import (
    ImageOnlyDetectionConfig,
    ImageOnlyDetectionResult,
    detect_image_only_watermark,
)
from main.methods.geometry import (
    ATTENTION_RELATION_COMPONENT_NAMES,
    ATTENTION_RELATION_COMPONENT_WEIGHTS,
    DIRECT_QK_RELATION_SOURCE,
    AttentionAlignmentResult,
    AttentionGeometryGradient,
    AttentionGeometryUpdate,
    AttentionRelationDescriptor,
    DifferentiableAttentionRecorder,
    QKAttentionRelation,
    attention_geometry_score,
    attention_relation_component_protocol,
    build_attention_relation_descriptor,
    compute_attention_geometry_gradient,
    optimize_attention_geometry_update,
    qk_self_attention,
    recover_attention_affine_alignment,
    validate_attention_relation_component_weights,
)
from main.methods.method_definition import (
    METHOD_DEFINITION_SCHEMA,
    semantic_conditioned_latent_method_definition,
    semantic_conditioned_latent_method_definition_digest,
)
from main.methods.semantic import (
    BranchRiskConfig,
    BranchRiskFieldBundle,
    CarrierRiskField,
    build_branch_risk_fields,
)
from main.methods.subspace import (
    ExactJacobianLinearization,
    JacobianNullSpaceResult,
    PSDConjugateGradientResult,
    build_exact_jacobian_linearization,
    exact_jvp,
    generate_keyed_candidate_directions,
    solve_psd_conjugate_gradient,
    solve_jacobian_null_space,
)

__all__ = [
    "ATTENTION_RELATION_COMPONENT_NAMES",
    "ATTENTION_RELATION_COMPONENT_WEIGHTS",
    "DIRECT_QK_RELATION_SOURCE",
    "AttentionAlignmentResult",
    "AttentionGeometryGradient",
    "AttentionGeometryUpdate",
    "AttentionRelationDescriptor",
    "BlindContentScore",
    "BranchRiskConfig",
    "BranchRiskFieldBundle",
    "CarrierRiskField",
    "DifferentiableAttentionRecorder",
    "ExactJacobianLinearization",
    "ImageOnlyDetectionConfig",
    "ImageOnlyDetectionResult",
    "JacobianNullSpaceResult",
    "KeyedTensorCarrier",
    "METHOD_DEFINITION_SCHEMA",
    "PSDConjugateGradientResult",
    "QKAttentionRelation",
    "attention_geometry_score",
    "attention_relation_component_protocol",
    "build_attention_relation_descriptor",
    "build_branch_risk_fields",
    "build_exact_jacobian_linearization",
    "build_low_frequency_template",
    "build_tail_robust_template",
    "compute_attention_geometry_gradient",
    "compute_blind_content_score",
    "detect_image_only_watermark",
    "exact_jvp",
    "generate_keyed_candidate_directions",
    "optimize_attention_geometry_update",
    "project_canonical_template",
    "qk_self_attention",
    "recover_attention_affine_alignment",
    "semantic_conditioned_latent_method_definition",
    "semantic_conditioned_latent_method_definition_digest",
    "validate_attention_relation_component_weights",
    "solve_psd_conjugate_gradient",
    "solve_jacobian_null_space",
]
