"""论文方法实现与机制变体。"""

from main.methods.algorithm_primitives import (
    CarrierPrimitive,
    ContentScoreResult,
    EvidenceDecisionResult,
    GeometryReliabilityResult,
    LatentMaskProjection,
    LatentUpdateComposition,
    RiskFieldParameters,
    SafeBasisEstimate,
    SemanticRiskField,
    build_semantic_risk_field,
    compose_latent_update,
    compute_content_score,
    decide_evidence_and_final,
    derive_attention_carrier_stub,
    derive_hf_carrier,
    derive_lf_carrier,
    estimate_safe_basis,
    evaluate_geometry_reliability,
    project_latent_mask,
)

__all__ = [
    "CarrierPrimitive",
    "ContentScoreResult",
    "EvidenceDecisionResult",
    "GeometryReliabilityResult",
    "LatentMaskProjection",
    "LatentUpdateComposition",
    "RiskFieldParameters",
    "SafeBasisEstimate",
    "SemanticRiskField",
    "build_semantic_risk_field",
    "compose_latent_update",
    "compute_content_score",
    "decide_evidence_and_final",
    "derive_attention_carrier_stub",
    "derive_hf_carrier",
    "derive_lf_carrier",
    "estimate_safe_basis",
    "evaluate_geometry_reliability",
    "project_latent_mask",
]
